library(dplyr)
library(ggplot2)
library(reshape2)
library(lubridate)

#Setting Working Directory.
setwd("C:/Jig12326")
getwd()

#Loading data.
cam<-read.table("Campaign_File.txt",header = T,sep = "\t")
cust<-read.table("Customers_File.txt",header = T,sep = "\t")
pro<-read.table("Products_File.txt",header = T,sep = "\t")
tran<-read.table("Transactions_File.txt",header = T,sep = "\t")
options(scipen = 999)

#Descriptive Statistics.
str(cam)
str(cust)
str(pro)
str(tran)

summary(cam)
summary(cust)
summary(pro)
summary(tran)

#Checking Missing Values.
colSums(is.na(cam))
colSums(is.na(cust))
colSums(is.na(pro))
colSums(is.na(tran))


#Q1. Based on the transactions, which product category dominates in terms of $ amount?

#Merging tables transaction and product (outer join).
tranpro<-merge(x=tran,y=pro,by="Product_Code")

#Descriptive Statistics of new data set.
str(tranpro)
summary(tranpro)

#querying the objective.
TS<-sum(tranpro$Items_Amount)
TS
tranpro%>%group_by(Product_Category)%>%summarise(Count=n(),Percentage_Count=n()/350241,
                                                 Total_Sales=sum(Items_Amount),Percentage_Sales=
                                                   Total_Sales/TS,Average=mean(Items_Amount))%>%
  ungroup()%>%arrange(-Total_Sales)%>%data.frame()->tranpro_table

#Arranging in descending order with respect to revenue.
tranpro_table%>%arrange(desc(revenue))

#Writing out the solution table in .csv format.
write.csv(tranpro_table,"Revenue Generated by Product Category.csv",row.names = F)


#=>Graphical Representation of Amount of Revenue Generation by Product Category.
tranpro%>%group_by(Product_Category)%>%summarize(Tot_Sales=sum(Items_Amount))%>%melt()->tot_sales

tot_sales$per_sales<-round(tot_sales$value/TS,2)

p<-ggplot(tot_sales,aes(x=Product_Category,y=value,fill=Product_Category))
p+geom_bar(stat="identity",alpha=0.7)+labs(fill="Product Category")+
  geom_text(aes(label=per_sales,colour=per_sales),vjust=-0.3,size=5)+theme_classic()+
  scale_fill_discrete(c=50,h=c(1,360),h.start =50)+guides(color=FALSE)+xlab("Product Category")+
  ylab("Sales in $")+ggtitle("Revenue Generated by Product Category")+
  scale_y_continuous(breaks=seq(0,35000000,5000000))

#---------------------OR---------------------

tranpro%>%filter(Items_Amount>0)%>%group_by(Product_Category)%>%summarise(Count=n(),Percentage_Count=n()/350241,
                                                                          Total_Sales=sum(Items_Amount),
                                                                          Percentage_Sales=Total_Sales/
                                                                            TS,Average=mean(Items_Amount))%>%
  ungroup()%>%arrange(-Total_Sales)%>%mutate(Contribution.Sales=rep("Product",7))%>%data.frame()->sales

sales$Percentage_Sales<-round(sales$Percentage_Sales,2)

q<-ggplot(sales,aes(x=Product_Category,y=Total_Sales,fill=Product_Category))
q+geom_bar(stat="identity",alpha=0.7)+geom_text(aes(label=Percentage_Sales,color=Percentage_Count),vjust=-0.4)+
  theme_classic()+scale_fill_discrete(c=50,h =c(1,300),h.start = 50)+guides(color=F)+
  ggtitle("Revenue Contribution by Product Category")+xlab("Product Category")+ylab("Sales in $")+
  scale_y_continuous(breaks=seq(0,35000000,5000000))



#=>Graphical Representation on Percentage of Total Number of Transactions conducted in Each Product Category.
tranpro%>%group_by(Product_Category)%>%summarize(Tot_Count=n())%>%ungroup%>%melt()->tot_count

tot_count$per_count<-round(tot_count$value/350241*100,2)

tot_count<-arrange(tot_count,desc(value))

l<-ggplot(tot_count,aes(x=Product_Category,y=value,fill=Product_Category))
l+geom_bar(stat="identity",alpha=0.7)+theme_classic()+labs(fill="Product Category")+
  geom_text(aes(label=per_count,colour=Product_Category),vjust=-0.3,size=5)+
  scale_fill_discrete(c=50,h=c(1,360),h.start =50)+guides(color=FALSE)+xlab("Product Category")+
  ylab("Number of Transactions")+ggtitle("Transactions in Each Product Category")+
  scale_y_continuous(breaks=seq(0,210000,10000))

#------------------OR-----------------

tranpro%>%filter(Items_Amount>0)%>%group_by(Product_Category)%>%summarise(Count=n(),Percentage_Count=n()/350241,
                                                                          Total_Sales=sum(Items_Amount),
                                                                          Percentage_Sales=Total_Sales/TS,
                                                                          Average=mean(Items_Amount))%>%
  ungroup()%>%arrange(-Total_Sales)%>%mutate(Contribution.Sales=rep("Product",7))%>%data.frame()->sales

sales$Percentage_Count<-round(sales$Percentage_Count,2)

r<-ggplot(sales,aes(x=Product_Category,y=Count,fill=Product_Category))
r+geom_bar(stat="identity",alpha=0.7)+geom_text(aes(label=Percentage_Count,color=Average),vjust=-0.4,size=3)+
  theme_classic()+scale_fill_discrete(c=50,h =c(1,250),h.start = 50)+guides(color=F)+
  ggtitle("Transactions by Product Category")+xlab("PRODUCT CATEGORY")+ylab("NUMBER OF TRANSACTIONS")+
  scale_y_continuous(breaks=seq(0,210000,10000))


# ANALYSIS
# Product Category 'Entertainment' dominates with more than 40% of the Total Revenue generated in 
# only 3% of total transactions. Thus clearly the average price of products of Entertainment category 
# is quite high resulting in low number of transactions yet high revenue generation.

# Even though 59% of the transactions were made in Category, 'MP3Player', its revenue contribution was only
# 27% followed by Category Hardware with 13% Revenue generation in 23% Transactions.


# ---------------------------------------------------------------------------------------------------------------

#Q2. Perform a suitable age grouping and find out contribution of each of the age group in terms of $ amount spent.

# Mergeing tables transaction and customer (outer join).
trancust<-merge(x=tran,y=cust,by="Card_ID")

# Descriptive Statistics.
str(trancust)
summary(trancust)

#Creating Var 'Age' from  Var Birth_Date.
trancust$Birth_Date<-ymd(trancust$Birth_Date)
yr<-duration(num = 1,units = "years")
trancust$age=interval(trancust$Birth_Date,Sys.Date())/yr
head(trancust$age,100)
tail(trancust$age,100)
trancust$age<-round(trancust$age)

# Grouping Age Var
trancust<-arrange(trancust,age)
trancust$age_grp<-cut(trancust$age,breaks=18)

# Calculating total expenditure
TS1<-sum(trancust$Items_Amount)
TS1

#Summaring data after suitable age grouping to calculate contribution of each of the age group 
#in terms of $ amount spent.
trancust%>%group_by(age_grp)%>%summarise(Count=n(),Percentage_Count=n()/350241,Total_Spend=sum(Items_Amount),
                                         Percentage_Spend=Total_Spend/TS1,Average=mean(Items_Amount))%>%
  ungroup()%>%arrange(age_grp)%>%data.frame()



#=>Graphical Representation of Amount of Dollars Spent by prople of different age groups.
trancust%>%group_by(age_grp)%>%summarize(Tot_Spent=sum(Items_Amount))%>%melt()->tot_spent

summary(tot_spent)

tot_spent$per_sum<-round(tot_spent$value/TS1,2)

tot_spent$cumu_persum<-cumsum(tot_spent$per_sum)

p<-ggplot(tot_spent,aes(x=age_grp,y=value,fill=age_grp))
p+geom_bar(stat="identity",alpha=0.7)+labs(fill="Age Group-Yrs")+geom_text(aes(label=per_sum,colour=per_sum),
                                                                           vjust=-0.3,size=5)+theme_classic()+
  scale_fill_discrete(c=50,h=c(1,300),h.start =50)+guides(color=FALSE)+xlab("Age Group in Years")+
  ylab("Amount Spent in $")+ggtitle("Amount Spent By Different Age Groups")+
  scale_y_continuous(breaks=seq(0,17000000,1000000))

#------------------OR-------------------

trancust%>%filter(Items_Amount>0)%>%group_by(age_grp)%>%summarise(Count=n(),Percentage_Count=n()/350241,
                                                                  Total_Contribution=sum(Items_Amount),
                                                                  Percentage_Contribution=round(Total_Contribution/TS1,2),
                                                                  Average=mean(Items_Amount))%>%ungroup()%>%
  arrange(-Total_Contribution)%>%data.frame()->Age_Sales

#Writing out the solution table in .csv format.
write.csv(Age_Sales,"Revenue Contribution by Age Group.csv",row.names = F)

a<-ggplot(Age_Sales,aes(x=age_grp,y=Total_Contribution,fill=age_grp))
a+geom_bar(stat="identity",alpha=0.5)+labs(fill="Age Group-Yrs")+
  geom_text(aes(label=Percentage_Contribution,color=Percentage_Contribution),vjust=-0.4,size=4)+
  theme_classic()+scale_fill_discrete(c=50,h =c(1,460),h.start = 50)+guides(color=F)+
  ggtitle("Contribution by Age")+xlab("Age Group in Years")+ylab("Total Contribution in $")+
  scale_y_continuous(breaks=seq(0,16500000,1000000))


#=>Graphical representation of number of transactions conducted by people of various age groups
trancust%>%group_by(age_grp)%>%summarize(Tot_Count=n())%>%ungroup%>%melt()->tot_cnt

summary(tot_cnt)

tot_cnt$per_cnt<-round(tot_cnt$value/350241*100,2)

l<-ggplot(tot_cnt,aes(x=age_grp,y=per_cnt,fill=age_grp))
l+geom_bar(stat="identity",alpha=0.7)+theme_classic()+labs(fill="Age Group_Yrs")+
  geom_text(aes(label=per_cnt,colour=per_cnt),vjust=-0.3,size=5)+scale_fill_discrete(c=75,h=c(1,150),h.start =50)+
  guides(color=FALSE)+xlab("Age Group in Years")+ylab("Percentage Number of Transactions")+
  ggtitle("Percent number of transactions by Different Age Groups")


#Analysis
#As expected, people in age group 45 to 60 spend the maximum and people of ages upto 35 and 75 onwards spend much less. 
#Also clearly, expenditure age group wise is normally distributed with people of age group 50 to 55 spending the most. 
#Number of transactions are also maximum in the age group 45yrs to 60 yrs.


#-----------------------------------------------------------------------------------------------------------------

#Q3. Find the response rate to the campaign. Also identify the age group of customers where response rate is high. Is there a consistent trend?
summary(cam)

#Response Rate to the Campaign
cam%>%group_by(Campaign_Responce)%>%summarise(Count=n(),Percentage_Count=n()/5957*100)%>%
  arrange(-Campaign_Responce)%>%data.frame()

#Identify the age group of customers where response rate is high to understand if there is a consistent trend.
cust$Birth_Date<-ymd(cust$Birth_Date)
yr<-duration(num = 1,units = "years")
cust$age=interval(cust$Birth_Date,Sys.Date())/yr
cust$age<-round(cust$age)
cuscam<-merge(x=cam,y=cust,by="Card_ID",x.all=T)
str(cuscam)
summary(cuscam)
cuscam$age_grp1<-cut(cuscam$age,breaks=10)
summary(cuscam$age_grp1)

cuscam$Campaign_Responce<-as.factor(cuscam$Campaign_Responce)
table(cuscam$age_grp1,cuscam$Campaign_Responce)->table1
table1
Response_Rate<-table1[,"TRUE"]/rowSums(table1)*100
Response_Rate

write.csv(table1,"Response by Age Group.csv",row.names = F)
write.csv(Response_Rate,"Revenue Rate by Age Group.csv",row.names = F)


#Graphical Representation of Response Rate by Age Group
str(table1)
response<-as.data.frame(table1)
str(response)
names(response)<-c("Age Group","Response","Count")

resp_rate<-as.data.frame(Response_Rate)
names(resp_rate)<-c("Age Group in Yrs.","Response Rate")

#Analysis: <1> Response Rate to the Campaign is 5.4%. 
#<2> Response Rate is highest within Age Groups 34 to 42 yrs. 
# There is no consistent trend in Response Rate basis age groups.


#----------------------------------------------------------------------------------------------------------------

#Q4. Repeat the analysis above with "Tenure" of customer. 
# (Tenure will be defined as the time period between the Date of Registration and 31/12/2002)

#Creating Tenure Var
cuscam$Registration_Date<-ymd(cuscam$Registration_Date)
date=as.Date("31/12/2002",format="%d/%m/%Y")
str(date)
yr<-duration(num = 1,units = "years")
cuscam$Tenure=interval(cuscam$Registration_Date,date)/yr
summary(cuscam$Tenure)
cuscam$Tenure<-round(cuscam$Tenure)
cuscam$Tenure<-as.factor(cuscam$Tenure)
str(cuscam$Tenure)

#Calculating Response Rate
table(cuscam$Tenure,cuscam$Campaign_Responce)->table2
table2
Tenure_Rate<-table2[,"TRUE"]/rowSums(table2)*100
Tenure_Rate

#Analysis: Response rate is highest among customers with a tenure of 2 yrs. 
#There is no consistent response rate among customers basis tenure.


# ---------------------------------------------------------------------------------------------------------------

#Q5. Create a cross tab of response rate between Age and Tenure of customers. Do you observe anything?
table(cuscam$Tenure,cuscam$age_grp1,cuscam$Campaign_Responce)->table3
table3

response_rate<-table3/rowSums(table3)*100
response_rate

write.csv(table3,"Response Rate Between Age and Tenure of Customers.csv",row.names = F)

#Observation: Maximum Response has been received from customers of age group 43 to 68 across all Tenure.


# ---------------------------------------------------------------------------------------------------------------

#Q6. Which mode of payment is most popular? Is mode of payment affected by the time of transaction?

summary(trancust)
trancust$Registration_Date<-ymd(trancust$Registration_Date)
date=as.Date("31/12/2002",format="%d/%m/%Y")
str(date)
yr<-duration(num = 1,units = "years")
trancust$Tenure=interval(trancust$Registration_Date,date)/yr
summary(trancust$Tenure)
trancust$Tenure<-round(trancust$Tenure)

trancust$Timestamp<-ymd_hms(trancust$Timestamp)
trancust$hour<-hour(trancust$Timestamp)
str(trancust)
table(trancust$Payment_Method,trancust$hour)->table4
table4

Mode_Hr<-table4/rowSums(table4)*100
Mode_Hr

#Answer: The most popular method of payment is by Credit Card. 
# The mode of payment is not affected by time of Transaction.


#-----------------------------------------------------------------------------------------------------------------

#Q7. Do you think, based on the data, that age and gender has any impact on $ amount spent?

xtabs(trancust$Items_Amount~trancust$Gender+trancust$age_grp)->table5
table5
Impact<-table5/rowSums(table5)*100
Impact

#Analysis: Based on data, people of age group 40 to 65 spend the most. 
# But there is no significant impact in amount of money spent based on gender.


#----------------------------------------------------------------------------------------------------------------

#Q8. Produce a histogram for "tenure of a customer" separately for male and female customers.

trancust$Registration_Date<-ymd(trancust$Registration_Date)
date=as.Date("31/12/2002",format="%d/%m/%Y")
yr<-duration(num = 1,units = "years")
trancust$Tenure=interval(trancust$Registration_Date,date)/yr
trancust$Tenure<-round(trancust$Tenure,2)

tc<-ggplot(trancust,aes(x=Tenure,fill=Gender,color=Gender))
tc+geom_histogram(bins=10,position = "dodge",alpha=0.5)+theme_classic()+xlab("Tenure of Customer in Years")+
  ylab("Number of Customers")+ggtitle("Tenure of Customer as per Gender") 